#ifndef FERRET_OPTIONAL_H
#define FERRET_OPTIONAL_H

#include <stdint.h>
#include <stdbool.h>

// Optional type structure
// Each optional type T? is represented as:
//   typedef struct {
//       T value;
//       int is_some;  // 1 if value is present, 0 if none
//   } ferret_optional_T;

// The actual typedef struct definitions are generated by the code generator
// in the header files for each module that uses optional types.

// Macro to unwrap an optional value: opt ?? default
// Usage: FERRET_OPTIONAL_UNWRAP(optional_var, default_value)
#define FERRET_OPTIONAL_UNWRAP(opt, default_val) \
    ((opt).is_some ? (opt).value : (default_val))

// Helper macro to create a Some(value) optional
// Note: This is a generic helper, but specific types should use direct struct initialization
// Usage: FERRET_OPTIONAL_SOME(int32_t, 42) -> ((ferret_optional_int32_t){.value = 42, .is_some = 1})
#define FERRET_OPTIONAL_SOME(type, val) \
    ((ferret_optional_##type){.value = (val), .is_some = 1})

// Helper macro to create a None optional
// Usage: FERRET_OPTIONAL_NONE(int32_t) -> ((ferret_optional_int32_t){.value = 0, .is_some = 0})
#define FERRET_OPTIONAL_NONE(type) \
    ((ferret_optional_##type){.value = 0, .is_some = 0})

// Unwrap optional into out buffer using default when none.
// Layout: value bytes followed by 1-byte is_some flag at offset val_size.
void ferret_optional_unwrap_or(const void* opt, const void* default_val, void* out, uint64_t val_size);

#endif // FERRET_OPTIONAL_H
